/* Copyright 2023 David Porter <david@daporter.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include QMK_KEYBOARD_H

#include "features/achordion.h"
#include "swapper.h"

enum layers { BASE, SYM, NAV, NUM, ADJ };

enum custom_keycodes {
	// Custom oneshot mod implementation with no timers.
	SW_TAB = SAFE_RANGE, // Switch to next window         (cmd-tab)
};

// Home row mods.
#define HOME_R LGUI_T(KC_R)
#define HOME_S LALT_T(KC_S)
#define HOME_N LSFT_T(KC_N)
#define HOME_D LCTL_T(KC_D)
#define HOME_A RCTL_T(KC_A)
#define HOME_E RSFT_T(KC_E)
#define HOME_I LALT_T(KC_I)
#define HOME_H LGUI_T(KC_H)

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  J   │  G   │  M   │  P   │  V   │                  │ ; :  │ . !  │repeat│  /   │ ' "  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │HOME_R│HOME_S│HOME_N│HOME_D│  B   │                  │ , ?  │HOME_A│HOME_E│HOME_I│HOME_H│
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  X   │  F   │  L   │  C   │  W   │                  │  -   │  U   │  O   │  Y   │  K   │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │ nav  │  T   │    │  T   │  MO  │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[BASE] = LAYOUT(
    KC_J,   KC_G,   KC_M,   KC_P,   KC_V,         KC_SCLN, KC_DOT, QK_REP, KC_SLSH, KC_QUOT,
    HOME_R, HOME_S, HOME_N, HOME_D, KC_B,         KC_COMM, HOME_A, HOME_E, HOME_I,  HOME_H,
    KC_X,   KC_F,   KC_L,   KC_C,   KC_W,         KC_MINS, KC_U,   KC_O,   KC_Y,    KC_K,
                              MO(NAV), KC_T,   KC_SPC, MO(SYM)),


/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  `   │  <   │  >   │  @   │  ^   │                  │  &   │  $   │  [   │  ]   │      │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  !   │  -   │  +   │  =   │  :   │                  │  |   │  _   │  (   │  )   │  %   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │      │      │  *   │  \   │  ~   │                  │      │  #   │  {   │  }   │      │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[SYM] = LAYOUT(
    KC_GRV,  KC_LT,   KC_GT,   KC_AT,   KC_CIRC,       KC_AMPR, KC_DLR,  KC_LBRC, KC_RBRC, _______,
    KC_EXLM, KC_MINS, KC_PLUS, KC_EQL,  KC_COLN,       KC_PIPE, KC_UNDS, KC_LPRN, KC_RPRN, KC_PERC,
    XXXXXXX, XXXXXXX, KC_ASTR, KC_BSLS, KC_TILD,       _______, KC_HASH, KC_LCBR, KC_RCBR, XXXXXXX,
                               _______,   _______,   _______ ,   _______),

/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │ esc  │ back │ stab │ fwd  │      │                  │ pgup │ home │  up  │ end  │ caps │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │G(KC_T│G(KC_K│G(KC_J│ win  │      │                  │ pgdn │ left │ down │right │ del  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │                  │      │ bspc │ tab  │      │      │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[NAV] = LAYOUT(
    KC_ESC,    KC_WBAK, SW_TAB, KC_WFWD,        XXXXXXX,         KC_PGUP,   KC_HOME,   KC_UP,     KC_END,    KC_CAPS,
    G(KC_TAB), G(KC_K), G(KC_J), OSM(MOD_LGUI), XXXXXXX,         KC_PGDN,   KC_LEFT,   KC_DOWN,   KC_RGHT,   KC_DEL,
    XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,         XXXXXXX,   KC_BSPC,   KC_TAB,    XXXXXXX,   XXXXXXX,
                                       _______,   _______,   G(KC_SPC),   _______),

/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  F6  │  F4  │  F2  │ F10  │  F8  │                  │  F9  │  F1  │  F3  │  F5  │  F7  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  6   │  4   │  2   │  0   │  8   │                  │  9   │  1   │  3   │  5   │  7   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │                  │      │      │      │      │      │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[NUM] = LAYOUT(
    KC_F6,   KC_F4,   KC_F2,   KC_F10,  KC_F8,          KC_F9,   KC_F1,   KC_F3,   KC_F5,   KC_F7,
    KC_6,    KC_4,    KC_2,    KC_0,    KC_8,           KC_9,    KC_1,    KC_3,    KC_5,    KC_7,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                 _______, _______,   _______, _______),

/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │      │      │ play │      │bri up│                  │      │      │vol up│      │scrlk │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │ win  │ alt  │shift │ ctrl │bri dn│                  │      │      │vol dn│      │      │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │QK_BOO│      │      │      │      │                  │      │      │ mute │      │      │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[ADJ] = LAYOUT(
    XXXXXXX,         XXXXXXX,         KC_MPLY,         XXXXXXX,         KC_BRIU,         XXXXXXX,   XXXXXXX,    KC_VOLU,    XXXXXXX,    KC_SCRL,
    OSM(MOD_LGUI),   OSM(MOD_LALT),   OSM(MOD_LSFT),   OSM(MOD_LCTL),   KC_BRID,         XXXXXXX,   XXXXXXX,    KC_VOLD,    XXXXXXX,    XXXXXXX,
    QK_BOOT,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,   XXXXXXX,    KC_MUTE,    XXXXXXX,    XXXXXXX,
                                                                _______,   _______,   _______,   _______),

};

// clang-format on

/*
 * Tri-state layers.
 */

layer_state_t layer_state_set_user(layer_state_t state)
{
	return update_tri_layer_state(state, SYM, NAV, NUM);
}

/*
 * Combos.
 */

const uint16_t PROGMEM combo_t_sym[] = { KC_T, MO(SYM), COMBO_END };
const uint16_t PROGMEM combo_a_i[] = { HOME_A, HOME_I, COMBO_END };
const uint16_t PROGMEM combo_rep_slsh[] = { QK_REP, KC_SLSH, COMBO_END };
const uint16_t PROGMEM combo_dot_slsh[] = { KC_DOT, KC_SLSH, COMBO_END };
const uint16_t PROGMEM combo_j_g[] = { KC_J, KC_G, COMBO_END };
const uint16_t PROGMEM combo_y_k[] = { KC_Y, KC_K, COMBO_END };
const uint16_t PROGMEM combo_n_e[] = { HOME_N, HOME_E, COMBO_END };

enum combo_events {
	T_SYM,
	A_I,
	REP_SLSH,
	DOT_SLSH,
	J_G,
	Y_K,
	N_E,
};

combo_t key_combos[] = {
	[T_SYM] = COMBO(combo_t_sym, MO(ADJ)),
	[A_I] = COMBO(combo_a_i, KC_ENT),
	[REP_SLSH] = COMBO(combo_rep_slsh, KC_BSPC),
	[DOT_SLSH] = COMBO(combo_dot_slsh, C(KC_BSPC)),
	[J_G] = COMBO(combo_j_g, KC_Z),
	[Y_K] = COMBO(combo_y_k, KC_Q),
	[N_E] = COMBO(combo_n_e, CW_TOGG),
};

/*
 * Swapper.
 */

bool sw_win_active = false;

bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
	if (!process_achordion(keycode, record)) {
		return false;
	}
	update_swapper(&sw_win_active, KC_LCTL, KC_TAB, SW_TAB, keycode,
		       record);

	return true;
}

void matrix_scan_user(void)
{
	achordion_task();
}
